#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : tb_top.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Wed Aug 25 21:04:38 CST 2021
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: tb_top.sh [-help]
# usage: tb_top.sh [-lib_map_path]
# usage: tb_top.sh [-noclean_files]
# usage: tb_top.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'tb_top.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64 -kdb -v2005"
vhdlan_opts="-full64"
#vcs_elab_opts="-full64 -debug_pp -licqueue -l elaborate.log +lint=PCWM -P /tools/synopsys/verdi/R-2020.12-1/share/PLI/VCS/linux64/novas.tab /tools/synopsys/verdi/Q-2020.03/share/PLI/VCS/linux64/pli.a -kdb -lca"
vcs_elab_opts="-full64 -debug_pp -licqueue -l elaborate.log +lint=PCWM -P /tools/synopsys/verdi/R-2020.12-1/share/PLI/VCS/linux64/novas.tab /tools/synopsys/verdi/R-2020.12-1/share/PLI/VCS/linux64/pli.a"
vcs_sim_opts="-kdb -lca -ucli -licqueue -l simulate.log"

#vlogan_opts="-full64"
#vhdlan_opts="-full64"
#vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
#vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xil_defaultlib)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "tb_top.sh - Script generated by export_simulation (Vivado v2020.1 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../include" \
    "$ref_dir/../../src/control.v" \
    "$ref_dir/../../src/mvp.v" \
    "$ref_dir/../../src/mvp_axil.v" \
    "$ref_dir/../../src/mvp_top.v" \
    "$ref_dir/../../src/common/modadd.v" \
    "$ref_dir/../../src/common/modmul.v" \
    "$ref_dir/../../src/common/modsub.v" \
    "$ref_dir/../../src/common/modsubred.v" \
    "$ref_dir/../../src/mux/mux_seq.v" \
    "$ref_dir/../../src/axi/data_trimmer.v" \
    "$ref_dir/../../src/axi/ksk_buffer.v" \
    "$ref_dir/../../src/axi/pre_input_transposer.v" \
    "$ref_dir/../../src/axi/out_output_transposer.v" \
    "$ref_dir/../../src/axi/axi_axi2bram.v" \
    "$ref_dir/../../src/axi/axi_axis2bram.v" \
    "$ref_dir/../../src/axi/axi_bram2axi.v" \
    "$ref_dir/../../src/axi/axi_bram2axis.v" \
    "$ref_dir/../../src/axi/axi_data_rd_top.v" \
    "$ref_dir/../../src/axi/axi_data_wr_top.v" \
    "$ref_dir/../../src/monox/cross_aggressive_seq.v" \
    "$ref_dir/../../src/monox/monox_aggressive_seq.v" \
    "$ref_dir/../../src/monox/shuffle_seq.v" \
    "$ref_dir/../../src/ntt/ntt_core.v" \
    "$ref_dir/../../src/ntt/ntt_cu.v" \
    "$ref_dir/../../src/ntt/ct_butterfly.v" \
    "$ref_dir/../../src/intt/gs_butterfly.v" \
    "$ref_dir/../../src/intt/halfred.v" \
    "$ref_dir/../../src/intt/intt_core.v" \
    "$ref_dir/../../src/intt/intt_cu.v" \
    "$ref_dir/../../src/ntt_intt_common/addred.v" \
    "$ref_dir/../../src/ntt_intt_common/barrett.v" \
    "$ref_dir/../../src/ntt_intt_common/ntt_pe_swap.v" \
    "$ref_dir/../../src/ntt_intt_common/mulred.v" \
    "$ref_dir/../../src/ntt_intt_common/mult.v" \
    "$ref_dir/../../src/ntt_intt_common/single_port_rom.v" \
    "$ref_dir/../../src/ntt_intt_common/subred.v" \
    "$ref_dir/../../src/ntt_intt_common/tf_rom_wrapper.v" \
    "$ref_dir/../../src/vpu2/vpu2_datapath.v" \
    "$ref_dir/../../src/vpu2/vpu2_top.v" \
    "$ref_dir/../../src/vpu3/vpu3_datapath.v" \
    "$ref_dir/../../src/vpu3/vpu3_top.v" \
    "$ref_dir/../../src/sys_integration/mux_monox_seq.v" \
    "$ref_dir/../../src/sys_integration/vpu_addx_mux_monox_seq.v" \
    "$ref_dir/../../src/sys_integration/vpu_addx_seq.v" \
    "$ref_dir/../../src/preprocess/poly_ram.v" \
    "$ref_dir/../../src/preprocess/polyvec_ram.v" \
    "$ref_dir/../../src/preprocess/preprocess_top_chisel.v" \
    "$ref_dir/../../src/preprocess/preprocess_top.v" \
    "$ref_dir/../../src/preprocess/simple_dual_ram.v" \
    "$ref_dir/../../src/DP/dp_core.v" \
    "$ref_dir/../../src/DP/dp_ctxt_polyvec.v" \
    "$ref_dir/../../src/DP/dp_tripple_pp_buffer.v" \
    "$ref_dir/../../src/DP/dp_uram_polyvec.v" \
    "$ref_dir/../../src/DP/madd_top.v" \
    "$ref_dir/../../src/DP/madd.v" \
    "$ref_dir/../../src/DP/modmuladd.v" \
    "$ref_dir/../../src/reducebuffer/sp_uram.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../include" \
    "$ref_dir/../../src/axi/axi_read_master.sv" \
    "$ref_dir/../../src/axi/axi_write_master.sv" \
    "$ref_dir/../../src/axi/counter.sv" \
    "$ref_dir/../../src/addx/cross_aggressive_last_seq.v" \
    "$ref_dir/../../src/reduce_trace/poly_ram.sv" \
    "$ref_dir/../../src/reduce_trace/pp_buffer.sv" \
    "$ref_dir/../../src/reduce_trace/pp_buffer_x4.sv" \
    "$ref_dir/../../src/reduce_trace/reduce_trace.sv" \
    "$ref_dir/../../src/reduce_trace/stg3_sub.sv" \
    "$ref_dir/../../src/reducebuffer/reduce_buffer.v" \
    "$ref_dir/../../src/reducebuffer/uram_polyvec.v" \
    "$ref_dir/../../src/DP/dp_top.v" \
  2>&1 | tee -a vlogan.log

  # vlogan -work xil_defaultlib $vlogan_opts -sverilog +v2k +incdir+"$ref_dir/../../include" \
  # 2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +v2k +incdir+"$ref_dir/../../include" +incdir+"$ref_dir/../../sim/top_tb" \
    "$ref_dir/../../sim/top_tb/control_tb.sv" \
    "$ref_dir/../../sim/top_tb/fifo_fwft.v" \
    "$ref_dir/../../sim/top_tb/ram_model.sv" \
    "$ref_dir/../../sim/top_tb/tb_axi_bram.v" \
    "$ref_dir/../../sim/top_tb/current_tb_top.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.tb_top xil_defaultlib.glbl -o tb_top_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./tb_top_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./tb_top.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  else
    lib_map_path="$ref_dir/../../xilinx_vcs_lib"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key tb_top_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc tb_top_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./tb_top.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: tb_top.sh [-help]\n\
Usage: tb_top.sh [-lib_map_path]\n\
Usage: tb_top.sh [-reset_run]\n\
Usage: tb_top.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
