axi_demo_top
i_axi_top (
    .clk                    ( ap_clk                ),
    .rst_n                  ( ap_rst_n              ),
    .mvp_axi_awvalid        ( mvp_axi_awvalid       ),
    .mvp_axi_awready        ( mvp_axi_awready       ),
    .mvp_axi_awaddr         ( mvp_axi_awaddr        ),
    .mvp_axi_awlen          ( mvp_axi_awlen         ),
    .mvp_axi_wvalid         ( mvp_axi_wvalid        ),
    .mvp_axi_wready         ( mvp_axi_wready        ),
    .mvp_axi_wdata          ( mvp_axi_wdata         ),
    .mvp_axi_wstrb          ( mvp_axi_wstrb         ),
    .mvp_axi_wlast          ( mvp_axi_wlast         ),
    .mvp_axi_bvalid         ( mvp_axi_bvalid        ),
    .mvp_axi_bready         ( mvp_axi_bready        ),
    .mvp_axi_arvalid        ( mvp_axi_arvalid       ),
    .mvp_axi_arready        ( mvp_axi_arready       ),
    .mvp_axi_araddr         ( mvp_axi_araddr        ),
    .mvp_axi_arlen          ( mvp_axi_arlen         ),
    .mvp_axi_rvalid         ( mvp_axi_rvalid        ),
    .mvp_axi_rready         ( mvp_axi_rready        ),
    .mvp_axi_rdata          ( mvp_axi_rdata         ),
    .mvp_axi_rlast          ( mvp_axi_rlast         ),
    .ap_start               ( ap_start              ),
    .ap_done                ( ap_done               ),
    .ap_idle                ( ap_idle               ),
    .ap_ready               ( ap_ready              ),
    .ksk_ptr                ( ksk_ptr               ),
    .pre_ptr                ( pre_ptr               ),
    .output_ptr             ( output_ptr            ),
    .command                ( command               ),
    .level                  ( level                 ),
    .index                  ( index                 )
);
